### ISSUE TITLE
Not able to inject http request headers into client.js

### ISSUE THREAD

**Issue by dockter-84** [jupyter/kernel_gateway_demos#13]
This is a continuation of https://github.com/jupyter/jupyter-js-services/issues/132 with the new recommended test client.   Here's the current example of the HTTP request not passing HTTP headers...

The following installs the new client code:

``` console
rm -rf ~/kernel_gateway_demos
cd ~
git clone https://github.com/jupyter/kernel_gateway_demos
cd ~/kernel_gateway_demos/node_client_example
npm install
```

In `~/kernel_gateway_demos/node_client_example` create client2.js based on https://github.com/jupyter/kernel_gateway_demos/blob/master/node_client_example/client.js  with minor modifications based on the use of the `ajaxSettings` variable.   It looks like this:

``` javascript
// Copyright (c) Jupyter Development Team.
// Distributed under the terms of the Modified BSD License.

var xmlhttprequest = require('xmlhttprequest');
var ws = require('ws');
var fs = require('fs');

global.XMLHttpRequest = xmlhttprequest.XMLHttpRequest;
global.WebSocket = ws;

var PYTHON_EXAMPLE = fs.readFileSync('example.py', {encoding: 'utf-8'});
var SCALA_EXAMPLE = fs.readFileSync('example.scala', {encoding: 'utf-8'});

var jupyter = require('jupyter-js-services');

var kg_host = process.env.GATEWAY_HOST || '192.168.99.100:8888';
var baseUrl = 'http://' + kg_host;
var demo_lang = process.env.DEMO_LANG === 'scala' ? 'scala' : 'python';
var demo_code = (demo_lang === 'scala') ? SCALA_EXAMPLE : PYTHON_EXAMPLE;

var ajaxSettings = {
    user: 'test-user',
    password: 'test-password',
    requestHeaders: {
        'X-Spark-service-instance-id': 'test-instance-id'
    }
}

console.log('Targeting server:', kg_host);
console.log('Using demo lang:', demo_lang);

// get info about the available kernels and start a new one
jupyter.getKernelSpecs({ baseUrl:  baseUrl}).then((kernelSpecs) => {
    console.log('Available kernelspecs:', kernelSpecs);
    var options = {
        baseUrl: baseUrl,
        name: demo_lang,
        ajaxSettings: ajaxSettings,     
    };
    // request a kernel in the default language (python)
    console.log('Starting kernel:', demo_lang)
    jupyter.startNewKernel(options).then((kernel) => {
        // execute some code
        console.log('Executing sample code');
        var future = kernel.execute({ code: demo_code  } );
        future.onDone = () => {
            // quit when done
            process.exit(0);
        };
        future.onIOPub = (msg) => {
            // print received messages
            console.log('Received message:', msg);
        };
    });
});
```

Then run:

``` console
export GATEWAY_HOST=dev.spark.bluemix.net:8000/jupyter/v1
cd ~/kernel_gateway_demos/node_client_example
DEMO_LANG=python node client2.js
```

For your test, you may need to change the value of `GATEWAY_HOST` to a webserver where you can inspect the HTTP headers sent.

The Nginx log shows that this is what was in the request:

```
GET /jupyter/v1/api/kernelspecs?1461017685992 HTTP/1.1
User-Agent: node-XMLHttpRequest
Accept: */*
Host: dev.spark.bluemix.net:8000
Connection: close
```

The HTTP headers were not sent.

**Comment by blink1073** [comment]
Ah, your original request for the kernelspecs had no ajaxSettings, you need to pass the ajaxSettings as `jupyter.getKernelSpecs({ baseUrl:  baseUrl, ajaxSettings: ajaxSettings})`

**Comment by blink1073** [comment]
(I was able to get the demo working again, thank you @parente)

**Comment by parente** [comment]
@blink1073 good eyes.

We should probably add an error function to the demo so it doesn't just exit silently, but rather logs whatever it can first.

**Comment by dockter-84** [comment]
Your reference to `jupyter.getKernelSpecs({ baseUrl: baseUrl, ajaxSettings: ajaxSettings})`  leaves a lot to the imagination.  Can you cite an example that clearly shows what you mean?

**Comment by parente** [comment]
@dockter-84 The demo has a whole sequence of calls from asking what types of kernels are available to requesting a kernel to sending code to execute to that kernel.

The `getKernelSpecs` call is the first one to contact the proxy. In your modified sample, you do not pass any `ajaxSettings` to this call so the proxy does not have any to log. Move the definition of `ajaxSettings` out of the closure and try passing them to the one `getKernelSpecs` call in the sample.

**Comment by parente** [comment]
@dockter-84 Did the fix work for you? Can we close this one?

**Comment by dockter-84** [comment]
Yes, this is now working.  You may close this issue. Thank you!
