### ISSUE TITLE
scotch_demo build error

### ISSUE THREAD

**Issue by echowhisky** [jupyter/kernel_gateway_demos#19]
In the Makefile for the scotch_demo there appears to be a [typo](https://github.com/jupyter/kernel_gateway_demos/blob/1b20ae87cad1cba413647690a80f05fc3aeac275/scotch_demo/Makefile#L16) causing an error. When `make build` is run as-is in commit d755e0b it produces the following:

> flag provided but not defined: -no-cache
> See 'docker build --help'.
> make: **\* [build] Error 125

I'm running docker version 1.11.1 on OS X. Perhaps it works fine in other versions of docker, but in this case it appears to be fixable with an extra `-`  changing the line linked above to read:

``` make
@docker build --no-cache -t $(IMAGE) .
```

**Comment by parente** [comment]
Thanks for the catch!
