### ISSUE TITLE
Can I use POST methods?

### ISSUE THREAD

**Issue by guilhermecgs** [jupyter/kernel_gateway_demos#44]
All the examples use GET methods...

Can I use POST methods also?  Can you provide examples?

**Comment by poplav** [comment]
https://github.com/jupyter/kernel_gateway_demos/blob/b7fd80bda9e9b99f0c450c72ea5dc5aff55bd989/swagger-notebook-service/swagger-petstore-service/SwaggerPetstoreApi.ipynb

**Comment by poplav** [comment]
https://github.com/jupyter/kernel_gateway_demos/search?utf8=%E2%9C%93&q=post&type=

**Comment by parente** [comment]
Within the main repository, the API intro notebook has an example using the most common HTTP verbs, including `POST`: https://github.com/jupyter/kernel_gateway/blob/master/etc/api_examples/api_intro.ipynb

The http-mode documentation has a POST example in this section: http://jupyter-kernel-gateway.readthedocs.io/en/latest/http-mode.html#setting-the-response-status-and-headers
