### ISSUE TITLE
'KernelSpecManager' object has no attribute 'list_kernel_specs'

### ISSUE THREAD

**Issue by KharbandaArush** [jupyter/kernel_gateway_demos#50]
I am getting the below error. Because of this i am not able to Python3 as a Option under notebook. When i try to create a new notebook.

[E 08:25:21.831 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/Users/arushkharbanda/anaconda/lib/python3.6/site-packages/notebook/base/handlers.py", line 503, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/Users/arushkharbanda/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/Users/arushkharbanda/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/Users/arushkharbanda/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 285, in wrapper
        yielded = next(result)
      File "/Users/arushkharbanda/anaconda/lib/python3.6/site-packages/nb2kg/handlers.py", line 253, in get
        kernel_specs = yield gen.maybe_future(ksm.list_kernel_specs())
    AttributeError: 'KernelSpecManager' object has no attribute 'list_kernel_specs'
[E 08:25:21.836 NotebookApp] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Accept": "*/*",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|a4df3c05|201809df9ba79344a5ce70eeb60796dd|1499322332",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36",
      "Referer": "http://localhost:8889/tree?token=1d112b2ee475387f59e52e52dbca39e2580a6319ca201e62",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.8",
      "Cookie": "_xsrf=2|a4df3c05|201809df9ba79344a5ce70eeb60796dd|1499322332; JSESSIONID=8C4B6E15186887F0D1B04DB3B126704F; username-localhost-8888=\"2|1:0|10:1499448554|23:username-localhost-8888|44:YTA5MThkNGRhNGRhNDRkMmEzNTk1ZTZhNWMwZWZmZmU=|330d5a5e7fb0d9c08ce3634442f0da848d774c3bd520774eb0d97c07184bdc45\"; username-localhost-8889=\"2|1:0|10:1499482520|23:username-localhost-8889|44:NDUwZjEwMGU1Yzk5NGI0Nzg1Yjg1NmE1NWQ3MTBmY2E=|097ab2cb0784cb56d407d6704b482d91c19b0ecc14b136bb577116346406f413\""
    }

**Comment by amangarg96** [comment]
Hi, were you able to resolve this issue? @KharbandaArush 
If so, please let me know how you did it

**Comment by kevin-bates** [comment]
I suspect you may not have started the notebook instance with the appropriate class mappings.  Please ensure that both of the following have been performed...

```
jupyter serverextension enable --py nb2kg --sys-prefix
```

```
export KG_URL=http://kg-host:port
jupyter notebook \
  --NotebookApp.session_manager_class=nb2kg.managers.SessionManager \
  --NotebookApp.kernel_manager_class=nb2kg.managers.RemoteKernelManager \
  --NotebookApp.kernel_spec_manager_class=nb2kg.managers.RemoteKernelSpecManager 
```

Also, should you have more questions around **NB2KG**, feel free to post to its incubator repo: https://github.com/jupyter-incubator/nb2kg/issues since this project is essential for both [Kernel Gateway](https://github.com/jupyter/kernel_gateway) and [Enterprise Gateway](https://github.com/jupyter-incubator/enterprise_gateway).

**Comment by amangarg96** [comment]
Suggestion by @kevin-bates solved the issue for me
