### ISSUE TITLE
ImportError: cannot import name 'Type'

### ISSUE THREAD

**Issue by heiderich** [jupyter/kernel_gateway_demos#63]
After 

```
git clone https://github.com/jupyter/kernel_gateway_demos
cd kernel_gateway_demos/python_client_example
docker-compose build
```

the command 

`docker-compose up
`

produces the following error:

```
$ docker-compose up
Starting python_client_example_kernel_gateway_1 ... done
Starting python_client_example_nginx_1          ... done
Recreating python_client_example_client_1       ... done
Attaching to python_client_example_kernel_gateway_1, python_client_example_nginx_1, python_client_example_client_1
kernel_gateway_1  | [KernelGatewayApp] The Jupyter Kernel Gateway is running at: http://0.0.0.0:8888
client_1          | Traceback (most recent call last):
client_1          |   File "/src/client.py", line 5, in <module>
client_1          |     from tornado import gen
client_1          |   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 81, in <module>
client_1          |     from tornado.concurrent import (
client_1          |   File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 34, in <module>
client_1          |     from tornado.log import app_log
client_1          |   File "/usr/local/lib/python3.5/site-packages/tornado/log.py", line 34, in <module>
client_1          |     from tornado.escape import _unicode
client_1          |   File "/usr/local/lib/python3.5/site-packages/tornado/escape.py", line 27, in <module>
client_1          |     from tornado.util import unicode_type
client_1          |   File "/usr/local/lib/python3.5/site-packages/tornado/util.py", line 21, in <module>
client_1          |     from typing import (
client_1          | ImportError: cannot import name 'Type'
python_client_example_client_1 exited with code 1

```

This was observed by others. [This answer](https://stackoverflow.com/a/55214031) indicates that this might due to an incompatibility of the installed versions of jupyter/tornado with python 3.5.

**Comment by nscozzaro** [comment]
I'm getting the same error. Is there a fix?
![image](https://user-images.githubusercontent.com/15185105/58999412-b2418b80-87d3-11e9-8abf-303be9432b58.png)

**Comment by Duncanswilson** [comment]
it's because of the version of tornado and python 3.5
https://github.com/tornadoweb/tornado/issues/2623  
downgrade your tornado version to 5.1.1 and you'll be golden
`pip install tornado==5.1.1`

**Comment by stq054188** [comment]
> it's because of the version of tornado and python 3.5
> [tornadoweb/tornado#2623](https://github.com/tornadoweb/tornado/issues/2623)
> downgrade your tornado version to 5.1.1 and you'll be golden
> `pip install tornado==5.1.1`

@Duncanswilson  Your answer is right, thanks.

**Comment by christenvie** [comment]
> it's because of the version of tornado and python 3.5
> [tornadoweb/tornado#2623](https://github.com/tornadoweb/tornado/issues/2623)
> downgrade your tornado version to 5.1.1 and you'll be golden
> `pip install tornado==5.1.1`

wonderful idea it worked perfectly on my machine

**Comment by heiderich** [comment]
Another possibility is to use a recent python version (see #64).

**Comment by EmmaChung381** [comment]
> it's because of the version of tornado and python 3.5
> [tornadoweb/tornado#2623](https://github.com/tornadoweb/tornado/issues/2623)
> downgrade your tornado version to 5.1.1 and you'll be golden
> `pip install tornado==5.1.1`

I tried your idea, nut failed.

**Comment by s-ansa** [comment]
What if I want to use Python3.5 and have no control over installed libraries, at least when it comes to downgrading?

**Comment by kevin-bates** [comment]
It looks like `typing.Type` was added in [Python 3.5.3](https://docs.python.org/release/3.5.3/library/typing.html?highlight=typing#typing.Type), but not in <= [Python 3.5.2](https://docs.python.org/release/3.5.2/library/typing.html#module-typing), so there really isn't any choice other than downgrading Tornado or upgrading Python. 
 
Since this implies you're running 3.5.2 or older and [Python 3.5 is essentially end-of-life](https://devguide.python.org/#status-of-python-branches), you might ask your admin to upgrade Python instead.

**Comment by krishnaths** [comment]
> it's because of the version of tornado and python 3.5
> [tornadoweb/tornado#2623](https://github.com/tornadoweb/tornado/issues/2623)
> downgrade your tornado version to 5.1.1 and you'll be golden
> `pip install tornado==5.1.1`

Worked for me . Thanks !
